// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDfBZhwjqaPAaZlYU8ALojKvuIWCVVmuk',
    appId: '1:522626924574:web:5cae17797f28ffa5c8ee0f',
    messagingSenderId: '522626924574',
    projectId: 'chat-app-f82a9',
    authDomain: 'chat-app-f82a9.firebaseapp.com',
    storageBucket: 'chat-app-f82a9.firebasestorage.app',
    measurementId: 'G-Q7YJ6760M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJbmfBbum1u7XRwxVfhCiFoor_PWHQsxI',
    appId: '1:522626924574:android:4ff132276b8dd3c7c8ee0f',
    messagingSenderId: '522626924574',
    projectId: 'chat-app-f82a9',
    storageBucket: 'chat-app-f82a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRWfZjg5Fm829Wjs44E2wCasfAWrtvqik',
    appId: '1:522626924574:ios:de10852c5f3e0d67c8ee0f',
    messagingSenderId: '522626924574',
    projectId: 'chat-app-f82a9',
    storageBucket: 'chat-app-f82a9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRWfZjg5Fm829Wjs44E2wCasfAWrtvqik',
    appId: '1:522626924574:ios:de10852c5f3e0d67c8ee0f',
    messagingSenderId: '522626924574',
    projectId: 'chat-app-f82a9',
    storageBucket: 'chat-app-f82a9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDfBZhwjqaPAaZlYU8ALojKvuIWCVVmuk',
    appId: '1:522626924574:web:c2ec137b78ec2a82c8ee0f',
    messagingSenderId: '522626924574',
    projectId: 'chat-app-f82a9',
    authDomain: 'chat-app-f82a9.firebaseapp.com',
    storageBucket: 'chat-app-f82a9.firebasestorage.app',
    measurementId: 'G-DSBRP4GR3T',
  );
}
